version: "3.2"
services:
  sidekiq:
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec sidekiq
  web_1:
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec unicorn -p 3000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  web_2:
    build: .
    environment:
      RAILS_ENV: production
    command: bundle exec unicorn -p 3000
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true