---
:concurrency: 15
:pidfile: sidekiq.pid
staging:
 :concurrency: 10
production:
 :pidfile: sidekiq.pid
 :concurrency: 20
:queues:
 - default
 - [myqueue, 2]
:dynamic: true
:schedule:
 TestWorker:
  cron: '0 * * * *'
 CompleteAutoSupplyOrders:
  cron: '30 16 * * 1,2,3,4,5'
 OrderLineItemFromEquipmentAlert:
  cron: '0 * * * *'